### PR TITLE
Writeup of the NodeConf meeting

### PR DESCRIPTION
**Pull request by nebrius**

### CODE REVIEW

**Comment by jedireza** [comment]
:+1:

**Comment by Trott** [comment]
Looks good to me.

(Do you want comments on minor issues in the doc that are not related to content? For example, typographical nit: `makes up a their` => `makes up their`. Valuable polish or irksome nit-picking?)

**Comment by bnoordhuis** [comment]
I expected meeting notes but this reads more like a summary.  Is that intentional?

**Comment by nebrius** [comment]
@Trott yes, please do add those sorts of notes, and thanks for reading it over!

@bnoordhuis that is intentional, primarily for three reasons: a) there were ~4 hours of meetings, which is a lot to keep detailed notes on, b) we don't have minute by minute notes anyways and c) given the private, sensitive topics discussed at these meetings, confidentiality on the part of participants is critical.

**Comment by distracteddev** [comment]
LGTM

**Pull request merged**
